development:
  host: localhost
  adapter: postgresql
  database: development_instagram
  username: developer
  password: developer
  encoding: utf8
  pool: 5

test: &test
  host: localhost
  adapter: postgresql
  database: test_instagram
  username: developer
  password: developer
  encoding: utf8
  pool: 5
